# Generated by Django 2.0.13 on 2021-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField()),
                ('category_id', models.FloatField()),
            ],
        ),
    ]
